apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: term-get-order-tkn-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: term-get-order-tkn-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /order/generate_token
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /order/generate_token
