include:
- ./func/*
kind: ArchiveUploadSpec
name: func-B8k5

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: order-token-fn-5757c238-5ba0-4a75-9a54-572ffc85a635
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: order-token-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-B8k5
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-10-31T20:32:50Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: order-token-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: order-token-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.sign_term_and_generate_order_token
    packageref:
      name: order-token-fn-5757c238-5ba0-4a75-9a54-572ffc85a635
      namespace: default
  requestsPerPod: 10000
  resources: {}
